function left(){
document.writeln("<table width=\"228\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">");
document.writeln("  <tr>");
document.writeln("    <td><strong>一次内测：<\/strong><br \/>");
document.writeln("·2004年9月29日金秋佳节团圆日<br \/>");
document.writeln("《QQ堂》alpha1版本开放--糖果乐园正式招募成员!<br \/>");
document.writeln("·2004年10月14日QQ堂Alpha2版本火热推出<br \/>");
document.writeln("<strong>二次内测：<\/strong><br \/>");
document.writeln("·2004年11月25日--2004年12月18日 <br \/>");
document.writeln("《QQ堂》Alpha 4 Build 2版本于12月7日19:30正式更新 <br \/>");
document.writeln("·《QQ堂》历史上第一个结束内测的Alpha5版本12月24日发布·七剑Q堂　至尊法宝 <br \/>");
document.writeln("<strong>公测版本：<\/strong><br \/>");
document.writeln("·2004年12月29日--2005年1月12日 ");
document.writeln("公测开始，服务器对所有玩家开放。<br>");
document.writeln("·2005年1月12日");
document.writeln("  《QQ堂：小兵集训营》最新Alpha 5版本发布");
document.writeln("  增加了小兵频道栏目");
document.writeln("  <br>");
document.writeln("  ·2005年02月01日 ");
document.writeln("  《QQ堂：春之恋曲》版本发布");
document.writeln("  修正了退出游戏不算战绩的BUG，房间一个人可以挂机的BUG,推出玫瑰系列背景等。 ");
document.writeln("  <br>");
document.writeln("  ·  2005年3月8日 ");
document.writeln("  《QQ堂：试炼之章》最新Alpha7Build14发布");
document.writeln("  新增“比武大会”“夺宝奇兵”类型游戏模式和相关地图，音乐等“缤彩糖泡” ");
document.writeln("  “幻像魅影”“VIP卡”类型道具。频道地域划分选择栏。 ");
document.writeln("  <br>");
document.writeln("  ·  2005年3月28日《QQ堂：月光宝盒》最新Alpha8Build24发布");
document.writeln("  新增录像压缩功能.新增游戏中查看用户信息的功能.新增新的足球地图。<br>");
document.writeln("  ·  2005年4月29日");
document.writeln("  QQ堂Alpha9 Build14版本《QQ堂：比赛专用版》发布 ");
document.writeln("  新增比赛频道线上自动比赛系统，大厅玩家列表按照积分排名。<br>");
document.writeln("  ·  2005年4月9日 ");
document.writeln("  《QQ堂》中华英雄争霸赛横空出世 ");
document.writeln("  正式版本<br>");
document.writeln("  ·  2005年7月7日");
document.writeln("  《QQ堂：酷比一夏》正式1.0版发布");
document.writeln("  时间：2005年7月7日发布 ");
document.writeln("  新版本历经多次公测后的稳定成熟版。加入了新道具，人物外型做了改变。界面风格做了改进。 ");
document.writeln("  <br>");
document.writeln("  ·  2005年09月26 ");
document.writeln("  《泰坦归来》版本发布");
document.writeln("  穿泡绝技重出江湖之QQ堂新版本。推出紫钻。新地图机械地图。 ");
document.writeln("  <br>");
document.writeln("  ·  2005年12月22日");
document.writeln("  圣诞版《糖果盛年》版本发布至《糖果盛年》新春特别版b3b23 ");
document.writeln("  推出小喇叭，推箱子地图，推出BOSS任务活动。Boss专区开放。 ");
document.writeln("  <br>");
document.writeln("  ·  2006年3月24日");
document.writeln("  《 QQ 堂：船长密室》Beta4Build7 版本发布 ");
document.writeln("  开辟“静音纯游戏区 ”，改善小喇叭发送方式也作改善；增加了全新的BOSS任务关卡，添加新的道具收藏柜，新增的活动频道页面，新增家族系统。");
document.writeln("  <br>");
document.writeln("  ·  2006年4月27日");
document.writeln("  《我爱我家》版本发布");
document.writeln("  时间：2006年4月27日发布");
document.writeln("  改进家族功能；战斗快捷语言。 ");
document.writeln("  <br>");
document.writeln("  ·  2006年6月29日");
document.writeln("  《风云再起》版本发布 ");
document.writeln("  增加了新的音乐，新的BOSS，新的地图。家族声望系统，家族排行榜。  <\/td>");
document.writeln("  <\/tr>");
document.writeln("<\/table>");
document.writeln("<SCRIPT>	");
document.writeln("marqueetable = document.all.table01;");
document.writeln("scrollheight=327;");
document.writeln("stopscroll1=false; 	");
document.writeln("marqueetable.scrollTop=0; 	");
document.writeln("with(marqueetable){");
document.writeln(" style.height=scrollheight;");
document.writeln(" style.overflowX=\"hidden\";");
document.writeln(" style.overflowY=\"hidden\";");
document.writeln(" noWrap=true;");
document.writeln(" onmouseover=new Function(\"stopscroll1=true\");");
document.writeln(" onmouseout=new Function(\"stopscroll1=false\");");
document.writeln("}");
document.writeln(" startmarqueetop=0;");
document.writeln(" offsettop=0;");
document.writeln(" marqueestoptime=0;	");
document.writeln("function setmarqueetime()");
document.writeln("{");
document.writeln(" marqueetable.scrollTop=0;");
document.writeln(" setInterval(\"marqueeup()\",20);");
document.writeln("}");
document.writeln("setmarqueetime(); 	");
document.writeln("function marqueeup(){ 	");
document.writeln("if(stopscroll1==true) return; 	 ");
document.writeln("offsettop+=1; 	");
document.writeln("if(offsettop==540) 	 ");
document.writeln("{ 	");
document.writeln("marqueestoptime+=1; 		");
document.writeln("offsettop-=1; 		");
document.writeln("if(marqueestoptime==19)");
document.writeln("{offsettop=0; ");
document.writeln("marqueestoptime=0;");
document.writeln(" } ");
document.writeln("} 	  ");
document.writeln("else");
document.writeln(" {  ");
document.writeln(" 	startmarqueetop=marqueetable.scrollTop; ");
document.writeln("	 marqueetable.scrollTop+=1; 	");
document.writeln("	if(startmarqueetop==marqueetable.scrollTop)");
document.writeln("	{ ");
document.writeln("	marqueetable.scrollTop=0; ");
document.writeln("	marqueetable.scrollTop+=1; ");
document.writeln("	} ");
document.writeln(" } ");
document.writeln("} ");
document.writeln("<\/SCRIPT>")
document.writeln("")
}

function bottom(){
document.writeln("<div id=demo style=\"overflow:hidden; height:67px; width:660px; color:#892109\"> ");
document.writeln("<div id=demo1> ");
document.writeln(" <table width=\"670\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
document.writeln("  <tr>");
document.writeln("    <td align=\"center\"><img src=\"http://ossweb-img2.qq.com/images/qqtang/a20071226new/lo10.jpg\" width=\"102\" height=\"63\"><\/td>");
document.writeln("    <td align=\"center\">腾讯游戏频道<\/td>");
document.writeln("    <td>厚积薄发，一时盛事——《QQ堂》运营肇启于奥运年，转瞬已届三载，其间诸位同仁朝夕勤勉，一心用户，多有奉献。今奥运又将至，宛如轮回，谨祝《QQ堂》愈做愈好，与玩家朋友更多欢乐。<\/td>");
document.writeln("  <\/tr>");
document.writeln("  <tr>");
document.writeln("    <td width=\"18%\" align=\"center\"><a href=\"http:\/\/www.17173.com\/\" target=\"_blank\"><img src=\"http://ossweb-img2.qq.com/images/qqtang/a20071226new/lo07.jpg\" width=\"102\" height=\"63\" border=\"0\" \/><\/a><\/td>");
document.writeln("    <td width=\"21%\" align=\"center\">17173<\/td>");
document.writeln("    <td width=\"61%\"><p align=\"left\">值此《<span lang=\"EN-US\" xml:lang=\"EN-US\">QQ<\/span>堂》运营三周年之机，<span lang=\"EN-US\" xml:lang=\"EN-US\">17173.com<\/span>祝愿《<span lang=\"EN-US\" xml:lang=\"EN-US\">QQ<\/span>堂》蒸蒸日上，铸就卓越品牌形象，成为中国休闲网游企业之典范，与广大玩家、媒体携手并进，共创辉煌！<span lang=\"EN-US\" xml:lang=\"EN-US\"><\/span><\/p><\/td>");
document.writeln("  <\/tr>");
document.writeln("  <tr>");
document.writeln("    <td align=\"center\"><a href=\"http:\/\/www.pcgames.com.cn\/\" target=\"_blank\"><img src=\"http://ossweb-img2.qq.com/images/qqtang/a20071226new/lo11.jpg\" width=\"102\" height=\"63\" border=\"0\"><\/a><\/td>");
document.writeln("    <td align=\"center\">平洋游戏网<\/td>");
document.writeln("    <td>值此QQ堂三周年之际，太平洋游戏网携手广大QQ堂玩家致以最热烈的祝贺，祝愿QQ堂在2008年取得更大的成就！<\/td>");
document.writeln("  <\/tr>");
document.writeln("  <tr>");
document.writeln("    <td align=\"center\"><a href=\"http:\/\/www.1t1t.com\/\" target=\"_blank\"><img src=\"http://ossweb-img2.qq.com/images/qqtang/a20071226new/lo02.jpg\" width=\"102\" height=\"63\" border=\"0\"><\/a><\/td>");
document.writeln("    <td align=\"center\">1T1T网游先锋<\/td>");
document.writeln("    <td>热烈祝贺《QQ堂》成功运营3周年，为中国网游事业骏业肇兴，也顺祝《QQ堂》引领全国休闲网游潮流，再创网游神话！<br><\/td>");
document.writeln("  <\/tr>");
document.writeln("  <tr>");
document.writeln("    <td align=\"center\"><a href=\"http:\/\/www.52pk.com\/\" target=\"_blank\"><img src=\"http://ossweb-img2.qq.com/images/qqtang/a20071226new/lo04.jpg\" width=\"102\" height=\"63\" border=\"0\"><\/a><\/td>");
document.writeln("    <td align=\"center\">52PK<\/td>");
document.writeln("    <td> 恭贺腾讯游戏《QQ堂》三周年，祝愿它在今后的日子里，再接再励，取得更大的成功！<\/td>");
document.writeln("  <\/tr>");
document.writeln("  <tr>");
document.writeln("    <td align=\"center\"><a href=\"http:\/\/games.enet.com.cn\/\" target=\"_blank\"><img src=\"http://ossweb-img2.qq.com/images/qqtang/a20071226new/lo08.jpg\" width=\"102\" height=\"63\" border=\"0\"><\/a><\/td>");
document.writeln("    <td align=\"center\">硅谷动力游戏频道<\/td>");
document.writeln("    <td>在QQ堂成功运营三周年之际，仅此代表硅谷动力eNet游戏先锋祝愿QQ堂越来越红火，百尺竿头，更进一步。<\/td>");
document.writeln("  <\/tr>");
document.writeln("  <tr>");
document.writeln("    <td align=\"center\"><a href=\"http:\/\/www.5617.com\/\" target=\"_blank\"><img src=\"http://ossweb-img2.qq.com/images/qqtang/a20071226new/lo06.jpg\" width=\"102\" height=\"63\" border=\"0\"><\/a><\/td>");
document.writeln("    <td align=\"center\">5617<\/td>");
document.writeln("    <td>三年快乐相随，品牌今日铸就。贺《QQ堂》三周年生日，欢乐永相随。<\/td>");
document.writeln("  <\/tr>");
document.writeln("  <tr>");
document.writeln("    <td align=\"center\"><a href=\"http:\/\/www.56.com\/\" target=\"_blank\"><img src=\"http://ossweb-img2.qq.com/images/qqtang/a20071226new/lo09.jpg\" width=\"102\" height=\"63\" border=\"0\"><\/a><\/td>");
document.writeln("    <td align=\"center\">火狐游戏网<\/td>");
document.writeln("    <td>QQ堂三周年之际  祝贺 在线人数节节攀升，一 年更比一年火。<\/td>");
document.writeln("  <\/tr>");
document.writeln("  <tr>");
document.writeln("    <td align=\"center\"><a href=\"http:\/\/www.56.com\/\" target=\"_blank\"><img src=\"http://ossweb-img2.qq.com/images/qqtang/a20071226new/lo05.jpg\" width=\"102\" height=\"63\" border=\"0\"><\/a><\/td>");
document.writeln("    <td align=\"center\">56视频网<\/td>");
document.writeln("    <td>3年了,QQ堂陪我们走过的日日夜夜让大家成为了童话里的主角,在这里我们抛开一切的烦恼与顾虑,在这里我们结识了许多朋友,都希望未来仍然在一起放纵,一起欢笑!<\/td>");
document.writeln("  <\/tr>");
document.writeln("  <tr>");
document.writeln("    <td align=\"center\"><a href=\"http:\/\/6.cn\/\" target=\"_blank\"><img src=\"http://ossweb-img2.qq.com/images/qqtang/a20071226new/lo03.jpg\" width=\"102\" height=\"63\" border=\"0\" \/><\/a><\/td>");
document.writeln("    <td align=\"center\">六间房<\/td>");
document.writeln("    <td>一鸣惊人日中天　尊无二上势头添　三阳开泰齐相祝　恭贺Q堂新一年<\/td>");
document.writeln("  <\/tr>");
document.writeln("  <tr>");
document.writeln("    <td align=\"center\"><a href=\"http:\/\/www.ifensi.com\/\" target=\"_blank\"><img src=\"http://ossweb-img2.qq.com/images/qqtang/a20071226new/lo01.jpg\" width=\"102\" height=\"63\" border=\"0\"><\/a><\/td>");
document.writeln("    <td align=\"center\">粉丝网<\/td>");
document.writeln("    <td>粉丝网借助QQ堂上线三周年之际衷心祝愿QQ堂的全体用户在新的一年里在QQ堂中找到更多的乐趣。<\/td>");
document.writeln("  <\/tr>");
document.writeln("<\/table>");
document.writeln(" <\/div> ");
document.writeln(" <div id=demo2><\/div> ");
document.writeln(" <\/div> ");
document.writeln("<script> ");
document.writeln("var speed=30 ");
document.writeln(" demo2.innerHTML=demo1.innerHTML ");
document.writeln(" function Marquee(){ ");
document.writeln("if(demo2.offsetTop-demo.scrollTop<=0)   ");
document.writeln("demo.scrollTop-=demo1.offsetHeight \/\/demo跳到最顶端 ");
document.writeln("else{ ");
document.writeln("demo.scrollTop++ ");
document.writeln("   } ");
document.writeln("   } ");
document.writeln("   var MyMar=setInterval(Marquee,speed)");
document.writeln("   demo.onmouseover=function() {clearInterval(MyMar)} ");
document.writeln("   demo.onmouseout=function(){MyMar=setInterval(Marquee,speed)} ");
document.writeln("<\/script>")
}